# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'L3' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for L3
  pod 'Mapbox-iOS-SDK', '~> 4.8'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'Kingfisher', '~> 5.0'

  target 'L3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'L3UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
